language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer update --prefer-source

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcs --standard=PSR2 ./src ./tests/AssetManagerTest
  - php coverage-checker.php clover.xml 95

notifications:
  irc: "irc.freenode.org#zftalk.dev"
